name: Hello-SCM CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.13.1]
    env: 
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
      GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}
      NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
      NEXT_PUBLIC_SITE_URL: ${{secrets.NEXT_PUBLIC_SITE_URL}}
      NEXT_URL: ${{secrets.NEXT_URL}}
      AUTH_SECRET: ${{secrets.AUTH_SECRET}}
      NODE_ENV: ${{secrets.NODE_ENV}}
      UPLOADTHING_SECRET: ${{secrets.UPLOADTHING_SECRET}}
      UPLOADTHING_APP_ID: ${{secrets.UPLOADTHING_APP_ID}}
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
      EMAIL_SERVER_HOST: ${{secrets.EMAIL_SERVER_HOST}}
      EMAIL_SERVER_PORT: ${{secrets.EMAIL_SERVER_PORT}}
      EMAIL_SERVER_USER: ${{secrets.EMAIL_SERVER_USER}}
      EMAIL_SERVER_PASSWORD: ${{secrets.EMAIL_SERVER_PASSWORD}}
      EMAIL_FROM: ${{secrets.EMAIL_FROM}}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
